# coding: utf-8

"""
    Kubeflow Training SDK

    Python SDK for Kubeflow Training  # noqa: E501

    The version of the OpenAPI document: v1.6.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

from kubeflow.training.models import *
from kubeflow.training.models.github_com_kubeflow_common_pkg_apis_common_v1_job_status import GithubComKubeflowCommonPkgApisCommonV1JobStatus  # noqa: E501
from kubeflow.training.rest import ApiException

class TestGithubComKubeflowCommonPkgApisCommonV1JobStatus(unittest.TestCase):
    """GithubComKubeflowCommonPkgApisCommonV1JobStatus unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test GithubComKubeflowCommonPkgApisCommonV1JobStatus
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = kubeflow.training.models.github_com_kubeflow_common_pkg_apis_common_v1_job_status.GithubComKubeflowCommonPkgApisCommonV1JobStatus()  # noqa: E501
        if include_optional :
            return GithubComKubeflowCommonPkgApisCommonV1JobStatus(
                completion_time = None, 
                conditions = [
                    kubeflow.training.models.github/com/kubeflow/common/pkg/apis/common/v1/job_condition.github.com.kubeflow.common.pkg.apis.common.v1.JobCondition(
                        last_transition_time = None, 
                        last_update_time = None, 
                        message = '0', 
                        reason = '0', 
                        status = '0', 
                        type = '0', )
                    ], 
                last_reconcile_time = None, 
                replica_statuses = {
                    'key' : kubeflow.training.models.github/com/kubeflow/common/pkg/apis/common/v1/replica_status.github.com.kubeflow.common.pkg.apis.common.v1.ReplicaStatus(
                        active = 56, 
                        failed = 56, 
                        label_selector = None, 
                        selector = '0', 
                        succeeded = 56, )
                    }, 
                start_time = None
            )
        else :
            return GithubComKubeflowCommonPkgApisCommonV1JobStatus(
                conditions = [
                    kubeflow.training.models.github/com/kubeflow/common/pkg/apis/common/v1/job_condition.github.com.kubeflow.common.pkg.apis.common.v1.JobCondition(
                        last_transition_time = None, 
                        last_update_time = None, 
                        message = '0', 
                        reason = '0', 
                        status = '0', 
                        type = '0', )
                    ],
                replica_statuses = {
                    'key' : kubeflow.training.models.github/com/kubeflow/common/pkg/apis/common/v1/replica_status.github.com.kubeflow.common.pkg.apis.common.v1.ReplicaStatus(
                        active = 56, 
                        failed = 56, 
                        label_selector = None, 
                        selector = '0', 
                        succeeded = 56, )
                    },
        )

    def testGithubComKubeflowCommonPkgApisCommonV1JobStatus(self):
        """Test GithubComKubeflowCommonPkgApisCommonV1JobStatus"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
